### ISSUE TITLE
Missing database relation between mshop_order_base_product and mshop_product

### ISSUE THREAD

**Issue by verschuur** [aimeos/aimeos#9]
When looking at the DB schema, there seems to be a missing relation between `mshop_order_base_product` and `mshop_product`. It also isn't possible to create this relation as `mshop_order_base_product.prodid` is a `varchar(32)` while `mshop_product.id` is an `int(11)`.

Is this by design? If so, could you please give an explanation why? Our DBA would very much like to know :)

**Comment by aimeos** [comment]
Yes, this is by design. The data is organized in domains (domain driven design) and there are only references to other domains but no hard relations. This makes it possible to split the domains into separate databases (e.g. products in MySQL, orders in Oracle) and hard relations would cause much trouble if you delete the product and your ordered products would be removed too ;-)

**Comment by verschuur** [comment]
Ok, very informative and a nice setup. I'll pass the info along. Thanks for the quick response btw :).
